name: PR build

on:
  pull_request:
    branches: [main]

jobs:
    build-gradle:
        name: build and Test Managers
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup JDK 
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'semeru'
              
            - name: Print githash
              run: |
                echo $GITHUB_SHA > ./managers.githash

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: 6.9.2
            
            - name: Test and Build Managers
              run: |
               gradle -b galasa-managers-parent/build.gradle check publish \
               -Dorg.gradle.jvmargs=-Xmx4096M \
               -PsourceMaven=https://development.galasa.dev/main/maven-repo/extensions  \
               -PcentralMaven=https://repo.maven.apache.org/maven2/ \
               -PtargetMaven=${{github.workspace}}/repo

            - name: Build managers Image for testing
              uses: docker/build-push-action@v5
              with:
                context: .
                file: dockerfiles/dockerfile
                load: true
                tags: managers:test
                build-args: |
                   dockerRepository=harbor.galasa.dev
                   tag=main
          